export const modalStyle = ({ width }: { width: number }) => ({
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  bgcolor: 'background.paper',
  border: '2px solid #000',
  boxShadow: 24,
  paddingX: { xs: 2, sm: 4, md: 6 },
  paddingY: { xs: 2, sm: 3, md: 4 },
  width: `min(${width}px, calc(100vw - 24px))`,
  maxWidth: '100%',
  boxSizing: 'border-box',
  display: 'flex',
  flexDirection: 'column',
});
