export enum Pages {
  barcodesGenerator = '/barcodes-generator',
  invoiceConverter = '/invoice-converter',
  smSystem = '/sm-system',
  smSystemLogin = '/sm-system/login',
  smSystemTransfers = '/sm-system/transfers',
  smSystemImportProducts = '/sm-system/import-products',
  smSystemProductsDocuments = '/sm-system/products-documents',
  smSystemSuppliers = '/sm-system/suppliers-orders/suppliers',
  smSystemSupplierDetails = '/sm-system/suppliers-orders/suppliers/:supplierId',
  smSystemOrders = '/sm-system/suppliers-orders/orders',
  smSystemOrderDetails = '/sm-system/suppliers-orders/orders/:orderId',
  smSystemReports = '/sm-system/reports',
  smSystemUnfulfilledOrdersByTransfersReport = '/sm-system/unfulfilled-orders-by-transfers',
  smSystemPriceTagsGroups = '/sm-system/price-tags/groups',
  smSystemPriceTagsGroupDetails = '/sm-system/price-tags/groups/:groupId',
  smSystemEcommerceOrders = '/sm-system/ecommerce/orders',
  smSystemEcommerceOrderDetails = '/sm-system/ecommerce/orders/:orderId',
}
